### PR TITLE
Feature/add pipeline variables (#11)

### PR DESCRIPTION
**Pull request by thesattiraju**
* Add pipeline variables

* Better variables handling

### CODE REVIEW

**Review by charlottevdscheun — APPROVED** [review]

**Review by VivekLad-CG — APPROVED** [review]

**Review by VivekLad-CG — APPROVED** [review]

**Review by hirenkpa — APPROVED** [review]

**Comment by moattarwork** [comment]
Could you please merge this? your documentation is telling this is available but I'm getting 'Warning: Unexpected input(s) 'azure-pipeline-variables', valid inputs are ...` warning on the build

**Comment by hirenkpa** [comment]
> Could you please merge this? your documentation is telling this is available but I'm getting 'Warning: Unexpected input(s) 'azure-pipeline-variables', valid inputs are ...` warning on the build

I am also unable to merge this PR.

**Comment by moattarwork** [comment]
> > Could you please merge this? your documentation is telling this is available but I'm getting 'Warning: Unexpected input(s) 'azure-pipeline-variables', valid inputs are ...` warning on the build
> 
> I am also unable to merge this PR.

I'm wondering who is in charge of this repo. This is referenced by Microsoft Docs but the PR was open for 5 months after approval and no one has released it

**Comment by moattarwork** [comment]
Someone else tried this and couldn't wait for the merge 😄 https://github.com/Azure/pipelines/issues/40

**Comment by ladvivek7** [comment]
> > > Could you please merge this? your documentation is telling this is available but I'm getting 'Warning: Unexpected input(s) 'azure-pipeline-variables', valid inputs are ...` warning on the build
> > 
> > 
> > I am also unable to merge this PR.
> 
> I'm wondering who is in charge of this repo. This is referenced by Microsoft Docs but the PR was open for 5 months after approval and no one has released it

Hello ,
If you want, you may use below azure pipeline tool. In this we can pass variable from git to azure.

https://github.com/marketplace/actions/az-pipelines-action

I have done some changes in code and it is working for me.

**Pull request merged**
